### Dataset & DataLoader Class in PyTorch

In [1]:
from sklearn.datasets import make_classification
import torch

In [29]:
X, y = make_classification(
    n_samples=10,
    n_features=2,
    n_informative=2,
    n_redundant=0,
    n_classes=2,
    random_state=42,
)

In [30]:
from matplotlib import pyplot as plt

In [31]:
X.shape

(10, 2)

In [32]:
y

array([1, 0, 0, 0, 0, 1, 1, 1, 1, 0])

In [33]:
y.shape

(10,)

In [34]:
X = torch.tensor(X, dtype=torch.float32)
y = torch.tensor(y, dtype=torch.float32)

In [35]:
y 

tensor([1., 0., 0., 0., 0., 1., 1., 1., 1., 0.])

In [39]:
from torch.utils.data import DataLoader, TensorDataset, Dataset

In [40]:
class CustomDataset(Dataset):

  def __init__(self, features, labels):

    self.features = features
    self.labels = labels

  def __len__(self):

    return self.features.shape[0]

  def __getitem__(self, index):

    return self.features[index], self.labels[index]

In [41]:
dataset = CustomDataset(X, y)

In [42]:
len(dataset)

10

In [43]:
dataset[2]

(tensor([-2.8954,  1.9769]), tensor(0.))

In [44]:
dataloader = DataLoader(dataset, batch_size=2, shuffle=False)

In [45]:
for batch_features, batch_labels in dataloader:

  print(batch_features)
  print(batch_labels)
  print("-"*50)

tensor([[ 1.0683, -0.9701],
        [-1.1402, -0.8388]])
tensor([1., 0.])
--------------------------------------------------
tensor([[-2.8954,  1.9769],
        [-0.7206, -0.9606]])
tensor([0., 0.])
--------------------------------------------------
tensor([[-1.9629, -0.9923],
        [-0.9382, -0.5430]])
tensor([0., 1.])
--------------------------------------------------
tensor([[ 1.7273, -1.1858],
        [ 1.7774,  1.5116]])
tensor([1., 1.])
--------------------------------------------------
tensor([[ 1.8997,  0.8344],
        [-0.5872, -1.9717]])
tensor([1., 0.])
--------------------------------------------------


### Breast Cancer Dataset

In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [4]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

KeyError: "['id', 'Unnamed: 32'] not found in axis"

In [5]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [6]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [7]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [8]:
X_train_tensor = torch.from_numpy(X_train.astype(np.float32))
X_test_tensor = torch.from_numpy(X_test.astype(np.float32))
y_train_tensor = torch.from_numpy(y_train.astype(np.float32))
y_test_tensor = torch.from_numpy(y_test.astype(np.float32))

In [9]:
from torch.utils.data import Dataset, DataLoader

class CustomDataset(Dataset):

  def __init__(self, features, labels):

    self.features = features
    self.labels = labels

  def __len__(self):

    return len(self.features)

  def __getitem__(self, idx):

    return self.features[idx], self.labels[idx]



In [10]:
train_dataset = CustomDataset(X_train_tensor, y_train_tensor)
test_dataset = CustomDataset(X_test_tensor, y_test_tensor)

In [11]:
train_dataset[10]

(tensor([-0.0480,  1.8710, -0.0482, -0.1786,  0.2050,  0.1705, -0.5707, -0.1726,
         -0.9931, -0.1328, -0.1486,  0.5156,  0.0234, -0.2470,  0.0743,  0.0983,
         -0.3767,  0.7562,  0.0730,  0.6773, -0.2265,  1.2306, -0.2356, -0.3259,
         -0.3916, -0.1851, -0.7034, -0.1705, -1.0507, -0.0399]),
 tensor(0.))

In [12]:
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=True)

In [13]:
import torch.nn as nn


class MySimpleNN(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):

    out = self.linear(features)
    out = self.sigmoid(out)

    return out

In [14]:
learning_rate = 0.1
epochs = 25

In [15]:
# create model
model = MySimpleNN(X_train_tensor.shape[1])

# define optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

# define loss function
loss_function = nn.BCELoss()

In [16]:

# define loop
for epoch in range(epochs):

  for batch_features, batch_labels in train_loader:

    # forward pass
    y_pred = model(batch_features)

    # loss calculate
    loss = loss_function(y_pred, batch_labels.view(-1,1))

    # clear gradients
    optimizer.zero_grad()

    # backward pass
    loss.backward()

    # parameters update
    optimizer.step()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.2381250560283661
Epoch: 2, Loss: 0.33869004249572754
Epoch: 3, Loss: 0.03523039445281029
Epoch: 4, Loss: 0.1520386040210724
Epoch: 5, Loss: 0.02991678938269615
Epoch: 6, Loss: 0.06210850551724434
Epoch: 7, Loss: 0.29918578267097473
Epoch: 8, Loss: 0.0409059040248394
Epoch: 9, Loss: 0.19063329696655273
Epoch: 10, Loss: 0.33884409070014954
Epoch: 11, Loss: 0.0165778286755085
Epoch: 12, Loss: 0.27175647020339966
Epoch: 13, Loss: 0.11412309855222702
Epoch: 14, Loss: 0.2655159831047058
Epoch: 15, Loss: 0.027403581887483597
Epoch: 16, Loss: 0.08371562510728836
Epoch: 17, Loss: 0.2772026062011719
Epoch: 18, Loss: 0.016138900071382523
Epoch: 19, Loss: 0.18870410323143005
Epoch: 20, Loss: 0.026637479662895203
Epoch: 21, Loss: 0.32305094599723816
Epoch: 22, Loss: 0.03372452035546303
Epoch: 23, Loss: 0.018401717767119408
Epoch: 24, Loss: 0.024648068472743034
Epoch: 25, Loss: 0.0330137237906456


In [ ]:
model.eval() 
accuracy_list = []

with torch.no_grad():
    for batch_features, batch_labels in test_loader:
        y_pred = model(batch_features)
        y_pred = (y_pred > 0.8).float() 

        batch_accuracy = (y_pred.view(-1) == batch_labels).float().mean().item()
        accuracy_list.append(batch_accuracy)

overall_accuracy = sum(accuracy_list) / len(accuracy_list)
print(f'Accuracy: {overall_accuracy:.4f}')


Accuracy: 0.9531
