In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')

In [3]:
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [4]:
df.shape   

(569, 33)

In [5]:
df.drop(columns=['Unnamed: 32'], inplace=True)
df.drop(columns=['id'], inplace=True)

In [6]:
X_train, X_test, y_train, y_test = train_test_split(df.drop(columns=['diagnosis']), df['diagnosis'], test_size=0.2, random_state=42)

In [20]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((455, 30), (114, 30), (455,), (114,))

In [7]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [8]:
X_train

array([[-1.44075296, -0.43531947, -1.36208497, ...,  0.9320124 ,
         2.09724217,  1.88645014],
       [ 1.97409619,  1.73302577,  2.09167167, ...,  2.6989469 ,
         1.89116053,  2.49783848],
       [-1.39998202, -1.24962228, -1.34520926, ..., -0.97023893,
         0.59760192,  0.0578942 ],
       ...,
       [ 0.04880192, -0.55500086, -0.06512547, ..., -1.23903365,
        -0.70863864, -1.27145475],
       [-0.03896885,  0.10207345, -0.03137406, ...,  1.05001236,
         0.43432185,  1.21336207],
       [-0.54860557,  0.31327591, -0.60350155, ..., -0.61102866,
        -0.3345212 , -0.84628745]])

In [10]:
y_train

68     B
181    M
63     B
248    B
60     B
      ..
71     B
106    B
270    B
435    M
102    B
Name: diagnosis, Length: 455, dtype: object

In [11]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [12]:
y_train

array([0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0,

In [76]:
x_train_tensor = torch.from_numpy(X_train)
x_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [77]:
x_train_tensor.dtype, x_train_tensor.shape, y_train_tensor.dtype, y_train_tensor.shape

(torch.float64, torch.Size([455, 30]), torch.int32, torch.Size([455]))

In [78]:
x_train_tensor.shape, x_test_tensor.shape, y_train_tensor.shape, y_test_tensor.shape

(torch.Size([455, 30]),
 torch.Size([114, 30]),
 torch.Size([455]),
 torch.Size([114]))

In [79]:
x_train_tensor.shape

torch.Size([455, 30])

In [80]:
print(torch.ones(x_train_tensor.shape[1], 1))

tensor([[1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.]])


In [92]:
class MySimpleNN():

    def __init__(self, X):
        self.weights = torch.rand(X.shape[1], 1, dtype = torch.float64, requires_grad=True)
        self.bias = torch.rand(1, dtype = torch.float64, requires_grad=True)

    def forward(self, X):
        return torch.matmul(X, self.weights) + self.bias
        y_pred = torch.sigmoid(z)
        return y_pred
    
    def loss_function(self, y_pred, y):
        epsilon = 1e-7
        #clamp prediction to avoid log(0)
        y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

        loss = -(y * torch.log(y_pred) + (1 - y) * torch.log(1 - y_pred)).mean()
        return loss


In [136]:
learning_rate = 0.01
epochs = 25

In [ ]:
# Training pipeline
model = MySimpleNN(x_train_tensor)

# There are following steps with pipeline:
for epochs in range(epochs):

    # 1. Forward pass: Compute the model output (predictions) using the current weights and bias.
    y_pred = model.forward(x_train_tensor)
    # print (y_pred)
    # 2. Compute the loss: Calculate the loss using the predictions and the true labels.

    loss = model.loss_function(y_pred, y_train_tensor)
    # print (f'Epochs: {epochs}, Loss: {loss.item()}')
    # 3. Backward pass: Compute the gradients of the loss with respect to the weights and bias.
    loss.backward()

    # 4. Update weights and bias: Adjust the weights and bias using the gradients and the learning rate.
    with torch.no_grad():
        model.weights -= learning_rate * model.weights.grad
        model.bias -= learning_rate * model.bias.grad
        # Zero the gradients after updating the weights and bias.
        model.weights.grad.zero_()
        model.bias.grad.zero_()

    print(f'Epochs: {epochs}, Loss: {loss.item()}')

    # 6. Evaluate: After training, evaluate the model's performance on a test set.

Epochs: 0, Loss: 7.4608391575312245
Epochs: 1, Loss: 7.46082546167907
Epochs: 2, Loss: 7.460811986050719
Epochs: 3, Loss: 7.460798722804038
Epochs: 4, Loss: 7.460785664501918
Epochs: 5, Loss: 7.460772804085819
Epochs: 6, Loss: 7.4607601348514025
Epochs: 7, Loss: 7.460747650426053
Epochs: 8, Loss: 7.460735344748142
Epochs: 9, Loss: 7.460723212047851
Epochs: 10, Loss: 7.460711246829414
Epochs: 11, Loss: 7.460699443854682
Epochs: 12, Loss: 7.460687798127856
Epochs: 13, Loss: 7.460676304881331
Epochs: 14, Loss: 7.4606649595625045
Epochs: 15, Loss: 7.460653757821532
Epochs: 16, Loss: 7.460642695499913
Epochs: 17, Loss: 7.460631768619828
Epochs: 18, Loss: 7.460620973374208
Epochs: 19, Loss: 7.460610306117463
Epochs: 20, Loss: 7.460599763356792
Epochs: 21, Loss: 7.46058934174407
Epochs: 22, Loss: 7.460579038068248
Epochs: 23, Loss: 7.460568849248221
Epochs: 24, Loss: 7.46055877232615


In [86]:
model.weights

tensor([[0.2196],
        [0.1064],
        [0.1492],
        [0.2979],
        [0.3652],
        [0.2365],
        [0.2907],
        [0.2251],
        [0.5264],
        [0.4324],
        [0.9133],
        [0.2826],
        [0.5236],
        [0.8548],
        [0.5531],
        [0.4891],
        [0.9212],
        [0.5164],
        [0.4267],
        [0.0010],
        [0.7705],
        [0.9036],
        [0.7122],
        [0.5279],
        [0.4456],
        [0.4459],
        [0.3179],
        [0.1189],
        [0.2962],
        [0.3018]], dtype=torch.float64, requires_grad=True)

In [87]:
model.bias

tensor([0.6667], dtype=torch.float64, requires_grad=True)

In [ ]:
    # There are following steps with pipeline:
    # 1. Forward pass: Compute the model output (predictions) using the current weights and bias.
    # 2. Compute the loss: Calculate the loss using the predictions and the true labels.
    # 3. Backward pass: Compute the gradients of the loss with respect to the weights and bias.
    # 4. Update weights and bias: Adjust the weights and bias using the gradients and the learning rate.
    # 5. Repeat: Repeat steps 1-4 for a specified number of epochs or until convergence.
    # 6. Evaluate: After training, evaluate the model's performance on a test set.'

