In [1]:
import torch

In [2]:
print(torch.__version__)

1.12.0


In [3]:
if torch.cuda.is_available():
    print("GPU is available!")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. Using CPU.")

GPU is available!
Using GPU: NVIDIA GeForce RTX 3050 Ti Laptop GPU


## Creating a Tensor

In [4]:
torch.empty(2,3)

tensor([[1.0385e+21, 1.0357e-11, 2.1749e+23],
        [2.1747e+23, 6.7367e-10, 4.0326e-08]])

In [5]:
type(torch.empty(2,3))

torch.Tensor

In [6]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [9]:
torch.rand(2,3)

tensor([[0.3806, 0.7653, 0.8641],
        [0.4273, 0.1027, 0.6592]])

In [18]:
torch.manual_seed(10)
torch.rand(2,3)

tensor([[0.4581, 0.4829, 0.3125],
        [0.6150, 0.2139, 0.4118]])

In [21]:
torch.manual_seed(10)
torch.rand(2,3)

tensor([[0.4581, 0.4829, 0.3125],
        [0.6150, 0.2139, 0.4118]])

In [22]:
torch.tensor([2,3], dtype=torch.float32)

tensor([2., 3.])

### Tensors Shape

In [24]:
x = torch.tensor([[2,3,4], [4,5,6]])

In [25]:
x.shape

torch.Size([2, 3])

In [26]:
torch.empty_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [27]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [28]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [34]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.6938, 0.9693, 0.6178],
        [0.3304, 0.5479, 0.4440]])

### Data Types

In [30]:
x.dtype

torch.int64

In [31]:
torch.tensor([1.0, 2.0, 3.0], dtype=torch.int32)

C:\Users\samir\AppData\Local\Temp\ipykernel_17312\1968126410.py:1: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  torch.tensor([1.0, 2.0, 3.0], dtype=torch.int32)


tensor([1, 2, 3], dtype=torch.int32)

In [33]:
torch.tensor([1, 2, 3], dtype=torch.float32)

tensor([1., 2., 3.])

### Mathematical operattions

In [35]:
x = torch.rand(2,3)
x

tensor([[0.7041, 0.5573, 0.6959],
        [0.9849, 0.2924, 0.4823]])

In [36]:
x+2

tensor([[2.7041, 2.5573, 2.6959],
        [2.9849, 2.2924, 2.4823]])

In [37]:
x-2

tensor([[-1.2959, -1.4427, -1.3041],
        [-1.0151, -1.7076, -1.5177]])

In [38]:
x*2

tensor([[1.4082, 1.1145, 1.3917],
        [1.9699, 0.5847, 0.9647]])

In [39]:
x*100

tensor([[70.4093, 55.7251, 69.5862],
        [98.4929, 29.2374, 48.2329]])

In [41]:
(x+2)*100 %2

tensor([[0.4093, 1.7251, 1.5862],
        [0.4929, 1.2374, 0.2329]])

In [42]:
a = torch.rand(2,3)
b = torch.rand(2,3)

In [46]:
print(a)
print(b)

tensor([[0.6150, 0.4967, 0.4521],
        [0.0575, 0.0687, 0.0501]])
tensor([[0.0108, 0.0343, 0.1212],
        [0.0490, 0.0310, 0.7192]])


In [43]:
a + b

tensor([[0.6257, 0.5311, 0.5733],
        [0.1065, 0.0997, 0.7693]])

In [44]:
a - b

tensor([[ 0.6042,  0.4624,  0.3309],
        [ 0.0085,  0.0377, -0.6691]])

In [45]:
a / b

tensor([[57.1744, 14.4714,  3.7297],
        [ 1.1731,  2.2184,  0.0696]])

In [47]:
torch.abs(a)

tensor([[0.6150, 0.4967, 0.4521],
        [0.0575, 0.0687, 0.0501]])

In [48]:
torch.clamp(a, min=0.2, max=0.8)

tensor([[0.6150, 0.4967, 0.4521],
        [0.2000, 0.2000, 0.2000]])

### Reduction Operations

In [49]:
e = torch.randint(0, 10, (2,3))

In [50]:
e

tensor([[4, 5, 4],
        [0, 8, 9]])

In [51]:
torch.sum(e)

tensor(30)

In [52]:
torch.sum(e, dim=0)

tensor([ 4, 13, 13])

In [53]:
torch.sum(e, dim=1)

tensor([13, 17])

In [55]:
torch.mean(e, dtype=torch.float32)

tensor(5.)

In [56]:
torch.mean(e, dim=0, dtype=torch.float32)

tensor([2.0000, 6.5000, 6.5000])

In [57]:
torch.median(e)

tensor(4)

In [58]:
torch.prod(e)

tensor(0)

In [59]:
torch.argmin(e)

tensor(3)

### Matrix Operations

In [60]:
f = torch.randint(0, 10, (2,3))
g = torch.randint(0, 10, (2,3))

In [63]:
torch.matmul(f, g.T)

tensor([[ 96,  36],
        [110,  78]])

In [64]:
vector1 = torch.tensor([2,3,4])
vector2 = torch.tensor([4,5,6])

In [65]:
torch.dot(vector1, vector2)

tensor(47)

In [66]:
torch.transpose(f, 0, 1)

tensor([[3, 3],
        [0, 7],
        [9, 9]])

### Special functions

In [69]:
k = torch.randint(0, 10, (2,3)) 
k

tensor([[8, 9, 6],
        [9, 1, 9]])

In [70]:
torch.logical_not(k)

tensor([[False, False, False],
        [False, False, False]])

In [71]:
torch.log(k)

tensor([[2.0794, 2.1972, 1.7918],
        [2.1972, 0.0000, 2.1972]])

In [72]:
torch.sigmoid(k)

tensor([[0.9997, 0.9999, 0.9975],
        [0.9999, 0.7311, 0.9999]])

In [74]:
torch.softmax(k, dim=0, dtype=torch.float32)

tensor([[2.6894e-01, 9.9966e-01, 4.7426e-02],
        [7.3106e-01, 3.3535e-04, 9.5257e-01]])

In [75]:
torch.relu(k)

tensor([[8, 9, 6],
        [9, 1, 9]])

### Inplace Operations

In [76]:
n = torch.randint(0, 10, (2,3))
m = torch.randint(0, 10, (2,3))

In [77]:
m + n

tensor([[11,  5,  6],
        [18, 11,  6]])

In [78]:
print(m)
print(n)

tensor([[9, 4, 4],
        [9, 4, 4]])
tensor([[2, 1, 2],
        [9, 7, 2]])


In [ ]:
m.add_(n)  # _ represents in-place operation   

tensor([[11,  5,  6],
        [18, 11,  6]])

In [80]:
m

tensor([[11,  5,  6],
        [18, 11,  6]])

In [81]:
n

tensor([[2, 1, 2],
        [9, 7, 2]])