## Import Libraries

In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.DataFrame([[8,8,4], [7,9,5], [6,10,6], [5,12,7], [4,12,8], [3,13,9], [2,14,10], [1,15,11], [0,16,12]], columns= ['cgpa', 'profile_score', 'lpa'])

In [4]:
df

cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7
4     4             12    8
5     3             13    9
6     2             14   10
7     1             15   11
8     0             16   12

In [5]:
def initialize_parameters(layer_dims):
  
  np.random.seed(3)
  parameters = {}
  L = len(layer_dims)         

  for l in range(1, L):

    parameters['W' + str(l)] = np.ones((layer_dims[l-1], layer_dims[l]))*0.1
    parameters['b' + str(l)] = np.zeros((layer_dims[l], 1))
      

  return parameters

In [6]:
initialize_parameters([2, 2, 1])

{'W1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'W2': array([[0.1],
        [0.1]]),
 'b2': array([[0.]])}

In [7]:
def linear_forward(A_prev, W, b):
  
  Z = np.dot(W.T, A_prev) + b
  
  return Z

In [8]:
# Forward Propagation
def L_layer_forward(X, parameters):

  A = X
  L = len(parameters) // 2                  # number of layers in the neural network
  
  for l in range(1, L+1):
    A_prev = A 
    Wl = parameters['W' + str(l)]
    bl = parameters['b' + str(l)]
    # print("A"+str(l-1)+": ", A_prev)
    # print("W"+str(l)+": ", Wl)
    # print("b"+str(l)+": ", bl)
    # print("--"*20)

    A = linear_forward(A_prev, Wl, bl)
    # print("A"+str(l)+": ", A)
    # print("**"*20)
          
  return A,A_prev

In [9]:
X = df[['cgpa', 'profile_score']].values[0].reshape(2,1) # Shape(no of features, no. of training example)
y = df[['lpa']].values[0][0]

# Parameter initialization
parameters = initialize_parameters([2,2,1])

y_hat,A1 = L_layer_forward(X, parameters)

0.32 is the prediction

In [10]:
X

array([[8],
       [8]])

In [11]:
y

np.int64(4)

In [12]:
y_hat

array([[0.32]])

In [13]:
y_hat = y_hat[0][0]

In [14]:
def update_parameters(parameters,y,y_hat,A1,X):
  parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001 * 2 * (y - y_hat)*A1[0][0])
  parameters['W2'][1][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat)*A1[1][0])
  parameters['b2'][0][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat))

  parameters['W1'][0][0] = parameters['W1'][0][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0]*X[0][0])
  parameters['W1'][0][1] = parameters['W1'][0][1] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0]*X[1][0])
  parameters['b1'][0][0] = parameters['b1'][0][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0])

  parameters['W1'][1][0] = parameters['W1'][1][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0]*X[0][0])
  parameters['W1'][1][1] = parameters['W1'][1][1] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0]*X[1][0])
  parameters['b1'][1][0] = parameters['b1'][1][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0])

In [15]:
update_parameters(parameters,y,y_hat,A1,X)

In [16]:
parameters

{'W1': array([[0.10658137, 0.10658137],
        [0.10658137, 0.10658137]]),
 'b1': array([[0.00082267],
        [0.00082267]]),
 'W2': array([[0.111776],
        [0.111776]]),
 'b2': array([[0.119136]])}

In [17]:
X = df[['cgpa', 'profile_score']].values[0].reshape(2,1)
y = df[['lpa']].values[0][0]

parameters = initialize_parameters([2,2,1])

y_hat,A1 = L_layer_forward(X,parameters)
y_hat = y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)

parameters

{'W1': array([[0.10658137, 0.10658137],
        [0.10658137, 0.10658137]]),
 'b1': array([[0.00082267],
        [0.00082267]]),
 'W2': array([[0.111776],
        [0.111776]]),
 'b2': array([[0.119136]])}

In [18]:
X = df[['cgpa', 'profile_score']].values[1].reshape(2,1) 
y = df[['lpa']].values[1][0]

y_hat,A1 = L_layer_forward(X,parameters)
y_hat = y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)

parameters

{'W1': array([[0.11458955, 0.1168776 ],
        [0.11458955, 0.1168776 ]]),
 'b1': array([[0.0019667],
        [0.0019667]]),
 'W2': array([[0.12712927],
        [0.12712927]]),
 'b2': array([[0.13612818]])}

In [19]:
X = df[['cgpa', 'profile_score']].values[2].reshape(2,1)
y = df[['lpa']].values[2][0]

y_hat,A1 = L_layer_forward(X,parameters)
y_hat = y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)

parameters

{'W1': array([[0.12409711, 0.13272353],
        [0.12412266, 0.13276611]]),
 'b1': array([[0.00355129],
        [0.00355555]]),
 'W2': array([[0.14692424],
        [0.14731907]]),
 'b2': array([[0.15810417]])}

In [20]:
parameters = initialize_parameters([2,2,1])
epochs = 50

for i in range(epochs):

  Loss = []

  for j in range(df.shape[0]):

    X = df[['cgpa', 'profile_score']].values[j].reshape(2,1)
    y = df[['lpa']].values[j][0]

    y_hat,A1 = L_layer_forward(X,parameters)
    y_hat = y_hat[0][0]

    update_parameters(parameters,y,y_hat,A1,X)

    Loss.append((y-y_hat)**2)

  print('Epoch - ',i+1,'Loss - ',np.array(Loss).mean())

parameters

Epoch -  1 Loss -  44.99769307788389
Epoch -  2 Loss -  3.509982597690721
Epoch -  3 Loss -  6.9311788385168684
Epoch -  4 Loss -  6.859325742669538
Epoch -  5 Loss -  6.639091694469794
Epoch -  6 Loss -  6.404196185556228
Epoch -  7 Loss -  6.161934004214812
Epoch -  8 Loss -  5.919894571634756
Epoch -  9 Loss -  5.684910787223128
Epoch -  10 Loss -  5.461955566421975
Epoch -  11 Loss -  5.253918124146198
Epoch -  12 Loss -  5.061937114103689
Epoch -  13 Loss -  4.88592325256844
Epoch -  14 Loss -  4.725045526232197
Epoch -  15 Loss -  4.578095926603428
Epoch -  16 Loss -  4.443729452239179
Epoch -  17 Loss -  4.320607689400612
Epoch -  18 Loss -  4.207478549175833
Epoch -  19 Loss -  4.10321839108283
Epoch -  20 Loss -  4.006854279902793
Epoch -  21 Loss -  3.9175767801750823
Epoch -  22 Loss -  3.834748282763785
Epoch -  23 Loss -  3.757908224389949
Epoch -  24 Loss -  3.686774288956207
Epoch -  25 Loss -  3.6212373340803743
Epoch -  26 Loss -  3.5613469520335244
Epoch -  27 Loss - 

{'W1': array([[-0.87418764,  0.98319204],
        [-0.66404961,  2.05863957]]),
 'b1': array([[-0.00705548],
        [ 0.07320492]]),
 'W2': array([[0.50603199],
        [0.48648351]]),
 'b2': array([[0.48544956]])}

In [21]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [22]:
model = Sequential()
model.add(Dense(2, input_dim=2, activation='linear'))
model.add(Dense(1, activation='linear'))

C:\Users\samir\AppData\Roaming\Python\Python312\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [23]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [24]:
model.get_weights()

[array([[-1.117723  ,  0.8629557 ],
        [ 0.64474845, -0.7116762 ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-0.51572603],
        [ 0.3901055 ]], dtype=float32),
 array([0.], dtype=float32)]

In [25]:
new_weights = [np.array([[0.1, 0.1], [0.1, 0.1]]), np.array([0., 0.]), np.array([[0.1], [0.1]]), np.array([0.])]


In [26]:
model.set_weights(new_weights)

In [27]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [28]:
optimizer = keras.optimizers.Adam(learning_rate=0.001)
model.compile(optimizer=optimizer, loss='mean_squared_error')

In [ ]:
model.fit(df[['cgpa', 'profile_score']], df['lpa'], epochs=750)

Epoch 1/750
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 677ms/step - loss: 65.6194
Epoch 2/750
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 65.5017
Epoch 3/750
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 65.3829
Epoch 4/750
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 65.2633
Epoch 5/750
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 65.1426
Epoch 6/750
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 65.0210
Epoch 7/750
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 64.8983
Epoch 8/750
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 64.7746
Epoch 9/750
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 64.6499
Epoch 10/750
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 64.5242
Epoch 11/750
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 64.3974
Epoch 12/750
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 64.2695
Epoch 13/750
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 64.1405
Epoch 14/750
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 64.0104
Epoch 15/750
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 63.8793
Epo

In [ ]:
model.get_weights()

[array([[0.07220893, 0.07220893],
        [0.56412995, 0.56412995]], dtype=float32),
 array([0.38271293, 0.38271293], dtype=float32),
 array([[0.5180794],
        [0.5180794]], dtype=float32),
 array([0.26838875], dtype=float32)]